#raw reference genome data (required input!)
#-------------------------------------------
assembly_id: 'GCF_000002035.6_GRCz11'
mitochondrial_accession: 'NC_002333.2'
mitochondrial_tRNAs_from_mt_tRNADB: 'raw/references/tRNAdb/mit_from_tRNAdb.fst'
hc_genomic_tRNAs_from_GtRNAdb: 'raw/references/danRer11-tRNAs/danRer11-mature-tRNAs.fa'
downloaded_tRNAscanSE_summary: 'raw/references/danRer11-tRNAs/danRer11-tRNAs-detailed.out'
downloaded_tRNAscanSE_name_mapping: 'raw/references/danRer11-tRNAs/danRer11-tRNAs_name_map.txt'
housekeeping_refs: 'raw/references/houskeeping.fa' #TODO: currently deactivated; see rules in mapping.smk
raw_manual_refs: 'raw/manual.fa'


#processed reference genome
#-------------------------
ref_fasta_folder: 'resources/references/non-redundant'
genomic_refs: 'resources/references/non-redundant/genomic_fullScan.fa' # "all" tRNAscanSE predictions
genomic_split_hc_refs: 'resources/references/non-redundant/genomic_fullScan_highconfidence.fa'
genomic_split_additional_refs: 'resources/references/non-redundant/genomic_fullScan_additional.fa'
genomicBS_refs: 'resources/references/non-redundant/genomicBS_fullScan.fa'
#genomic_refs: 'resources/references/non-redundant/genomic_hc.fa' # highconfidence tRNAscanSE predictions
#genomicBS_refs: 'resources/references/non-redundant/genomicBS_hc.fa'
mitochondrial_refs: 'resources/references/non-redundant/mitochondrial_tRNADB.fa'
#mitochondrial_refs: 'resources/references/non-redundant/mitochondrial_gff.fa' # annotation errors!
#housekeeping_refs: 'resources/references/non-redundant/housekeeping.fa'


#mapping
#=======

#segemehl parameters
# see 10.1093/bioinformatics/btx756 for suggestions:--evalue 500 --differences 3 --maxinterval 1000 --accuracy 80
# default:

mapping: # on manual and selected refs
  MOCK:
    evalue: '500'
    accuracy: '80'
    maxinterval: '200' #1000
    difference: '3' # 2,3
  DM:
    evalue: '500'
    accuracy: '85'
    maxinterval: '200' #1000
    difference: '3' # 2,3
  BS:
    evalue: '500'
    accuracy: '90'
    maxinterval: '200' #1000
    difference: '3' # 2,3
    bisulfite: '1' #1

pre_mapping: # on all refs
  MOCK:
    evalue: '500'
    accuracy: '80'
    maxinterval: '200' #1000
    difference: '1' # 2,3
  DM:
    evalue: '500'
    accuracy: '85'
    maxinterval: '200' #1000
    difference: '1' # 2,3
  BS:
    evalue: '500'
    accuracy: '90'
    maxinterval: '200' #1000
    difference: '1' # 2,3
    bisulfite: '1' #1


#tRNA covariance model data (required input!)
#--------------------------------------------
min_raw_abundance_count_for_alignment: [['max all count', 10]]
min_raw_abundance_refs: 'resources/references/min_raw_abundance_tRNAs.fa'
rfam_alignment: 'raw/canonical_tRNA/RF00005.stockholm.txt'
rfam_cm: 'raw/canonical_tRNA/RF00005.cm'
canonical_positions_rfam_alignment : ["1", "2", "3", "4", "5", "6", "7", "8", "-",
         "9", "-", "10", "11", "12", "13", "14", "15", "16", "17", "-", "17a",
         "18", "19", "20", "20a", "20b", "-", "21", "22", "23", "24", "25",
         "26", "-", "27", "-", "28", "29", "30", "31", "32", "-", "33", "34",
         "35", "36", "37", "38", "39", "40", "41", "42", "-", "43", "44", "45",
         "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e",
         "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "46", "47", "-",
         "-", "48", "49", "50", "51", "-", "52", "53", "54", "-", "55", "56",
         "57", "-", "58", "59", "-", "60", "61", "62", "63", "64", "-", "65",
         "-", "66", "67", "68", "69", "70", "71", "72", "-", "73"] #currently not used

#refernce alignments
#-------------------
mitochondrial_alignment: 'resources/references/alignment/mitochondrial.fa'
genomic_hc_alignment: 'resources/references/alignment/genomic_hc.fa'
genomic_additional_alignment: 'resources/references/alignment/genomic_additional.fa'
all_tRNAs_alignment: 'resources/references/alignment/tRNAs.fa'
min_raw_abundance_alignment: 'resources/references/alignment/min_raw_abundance_tRNAs.fa'
selected_alignment: 'resources/references/alignment/selected_tRNAs.fa'


# canonical_positions in alignment
# 20a, 20b, 17a, 45-46

#samples (required input!)
#-------------------------
samples_tsv: 'config/samples.tsv'


# path to fastq files (provide fastq files within this folder)
#--------------------
raw_reads_folder: 'raw/raw_reads'


#reads preprocessing
#-------------------

poly_T_processing: 'ONtttt'


#min coverage cutoff after random assignment for getting high coverage refernces
#-------------------------------------------------------------------------------
min_coverage_per_ref: [['max max fraction', 0.0005]]

#clustering
#----------
#cluster_method: 'editdist'
#editdist_cluster_cutoff: 4
#toplevel_multimapper_cluster_fraction: 0.5


#reads_prefilter
#--------------
reads_filter: 'umi' # 'umi', 'none', 'cigar', umicigar
#reads_filter: 'none'

#abundance analysis
#------------------
abundance_score: 'random fraction'
#abundance_score: 'unique fraction'
#abundance_score: 'unique fraction (norm all)'
abundance_single_ref_cutoff: 0.002

# plot paramters
#---------------

min_coverage: 1000
replicate_markes: ['o', 's', '^', 'X', '+', 'D']
#replicate_markes: ['o', 'o', 'o', 'o', 'o', 'o']
min_C_fraction: 0.15 # min ref C fraction at position to make m5C call

# modification line plots:
#------------------------
modification_lineplots_cutoff:
  stop: 0.1
  m5C: 0.25
  #mismatch: 0.15
  other: 0.15

# reference set to use
#----------------------
ref_set: 'selected'
#ref_set: 'raw'
#ref_set: 'manual'

# Inosine anticodons based on Rappol et. al, 2024
inosine_no_filter: ['Ala-AGC','Arg-ACG','Ile-AAT','Leu-AAG',
                    'Pro-AGG','Ser-AGA','Thr-AGT','Val-AAC']
# Anticodons with G in position 34:
#Cys GCA
#Asn GTT
#Phe GAA
#Tyr GTA
#Gly GCC
#Asp GTC
#Asn GTT
#Cys GCA
#Asp GTC
#Tyr GTA
#Asn GTT
#Ser GCT
#Pro GGG
#Gly GCC
#Phe GAA
#Tyr GTA
#His GTG

g34_filter: ['Pro-GGG']

# config pca plots
#-----------------

pca_marker_dict:
  MOCK: 'o'
  DM: 's'
  BS: '^'

pca_color_dict:
  1: 'tab:blue'
  2: 'tab:orange'
  3: 'tab:green'
  4: 'tab:red'
  5: 'tab:purple'
  6: 'tab:brown'
  7: 'tab:pink'
